"""
EWG Tap Water Database - Health Standards
Source: https://www.ewg.org/tapwater/all-ewg-standards.php
Fetched: 2026-03-15

116 contaminants with EPA legal limits vs EWG health guidelines.
EWG standards are based purely on health science, not cost or feasibility.
"""

EWG_STANDARDS = {
    "1,1-DICHLOROETHANE": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 3.0,
        "ewg_limit_str": "3 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; change to the heart and blood vessels",
    },
    "1,1,2-TRICHLOROETHANE": {
        "epa_limit": 5.0,
        "epa_limit_str": "5 ppb",
        "ewg_limit": 0.3,
        "ewg_limit_str": "0.3 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Liver cancer; harm to the kidney; change to the central nervous system",
    },
    "1,2-DIBROMO-3-CHLOROPROPANE": {
        "epa_limit": 0.2,
        "epa_limit_str": "0.2 ppb",
        "ewg_limit": 0.0017,
        "ewg_limit_str": "0.0017 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Testicular cancer; harm to the male reproductive system; infertility",
    },
    "1,2-DICHLOROETHANE": {
        "epa_limit": 5.0,
        "epa_limit_str": "5 ppb",
        "ewg_limit": 0.4,
        "ewg_limit_str": "0.4 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the immune system; harm to the liver; harm to the kidney; harm to the brain and nervous system",
    },
    "1,2-DICHLOROPROPANE": {
        "epa_limit": 5.0,
        "epa_limit_str": "5 ppb",
        "ewg_limit": 0.5,
        "ewg_limit_str": "0.5 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Liver cancer; harm to the liver; harm to the kidney; change to blood cells",
    },
    "1,2,3-TRICHLOROPROPANE": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.0007,
        "ewg_limit_str": "0.0007 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer",
    },
    "1,2,4-TRICHLOROBENZENE": {
        "epa_limit": 70.0,
        "epa_limit_str": "70 ppb",
        "ewg_limit": 5.0,
        "ewg_limit_str": "5 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the adrenal gland; cancer",
    },
    "1,3-BUTADIENE": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.0103,
        "ewg_limit_str": "0.0103 ppb",
        "unit": "ppb",
        "source": "One-in-a-million cancer risk standard",
        "health_effects": "Cancer; harm to the brain and nervous system; harm to reproduction and child development",
    },
    "1,4-DIOXANE": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.35,
        "ewg_limit_str": "0.35 ppb",
        "unit": "ppb",
        "source": "One-in-a-million cancer risk standard",
        "health_effects": "Cancer; irritation of the lungs; harm to the kidney",
    },
    "P-DICHLOROBENZENE": {
        "epa_limit": 75.0,
        "epa_limit_str": "75 ppb",
        "ewg_limit": 6.0,
        "ewg_limit_str": "6 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the liver; harm to the kidney; harm to the thyroid",
    },
    "2,4-D": {
        "epa_limit": 70.0,
        "epa_limit_str": "70 ppb",
        "ewg_limit": 20.0,
        "ewg_limit_str": "20 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Hormone disruption; harm to the liver; harm to the kidney; harm to the thyroid",
    },
    "ALUMINUM": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 600.0,
        "ewg_limit_str": "600 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the brain and nervous system",
    },
    "ANTIMONY": {
        "epa_limit": 6.0,
        "epa_limit_str": "6 ppb",
        "ewg_limit": 1.0,
        "ewg_limit_str": "1 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the liver; change to the stomach and intestines",
    },
    "ARSENIC": {
        "epa_limit": 10.0,
        "epa_limit_str": "10 ppb",
        "ewg_limit": 0.004,
        "ewg_limit_str": "0.004 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the central nervous system; skin damage; increase the risk of heart disease, stroke and diabetes",
    },
    "ATRAZINE": {
        "epa_limit": 3.0,
        "epa_limit_str": "3 ppb",
        "ewg_limit": 0.1,
        "ewg_limit_str": "0.1 ppb",
        "unit": "ppb",
        "source": "EWG-recommended health guideline",
        "health_effects": "Harm to the developing fetus; hormone disruption; harm to the reproductive system; cancer",
    },
    "BARIUM": {
        "epa_limit": 2000.0,
        "epa_limit_str": "2 ppm",
        "ewg_limit": 700.0,
        "ewg_limit_str": "0.7 ppm",
        "unit": "ppb",
        "source": "Children's health-based limit for 10-day exposure",
        "health_effects": "Harm to the kidney; high blood pressure; harm to the heart and blood vessels",
    },
    "BENZENE": {
        "epa_limit": 5.0,
        "epa_limit_str": "5 ppb",
        "ewg_limit": 0.15,
        "ewg_limit_str": "0.15 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to blood cells; harm to the central nervous system; harm to the immune system",
    },
    "BENZO[A]PYRENE": {
        "epa_limit": 0.2,
        "epa_limit_str": "0.2 ppb",
        "ewg_limit": 0.007,
        "ewg_limit_str": "0.007 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the immune system; harm to reproduction and child development",
    },
    "BERYLLIUM": {
        "epa_limit": 4.0,
        "epa_limit_str": "4 ppb",
        "ewg_limit": 1.0,
        "ewg_limit_str": "1 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the stomach and intestines; harm to the lungs; harm to bones",
    },
    "BROMATE": {
        "epa_limit": 10.0,
        "epa_limit_str": "10 ppb",
        "ewg_limit": 0.1,
        "ewg_limit_str": "0.1 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer",
    },
    "BROMOCHLOROACETIC ACID": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.02,
        "ewg_limit_str": "0.02 ppb",
        "unit": "ppb",
        "source": "EWG-recommended health guideline",
        "health_effects": "Cancer; harm to fetal growth and development",
    },
    "BROMODICHLOROACETIC ACID": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.04,
        "ewg_limit_str": "0.04 ppb",
        "unit": "ppb",
        "source": "EWG-recommended health guideline",
        "health_effects": "Cancer; harm to fetal growth and development",
    },
    "BROMODICHLOROMETHANE": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.06,
        "ewg_limit_str": "0.06 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to reproduction and child development",
    },
    "BROMOFORM": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.5,
        "ewg_limit_str": "0.5 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to reproduction and child development",
    },
    "CADMIUM": {
        "epa_limit": 5.0,
        "epa_limit_str": "5 ppb",
        "ewg_limit": 0.04,
        "ewg_limit_str": "0.04 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the kidney; change in behavior",
    },
    "CARBOFURAN": {
        "epa_limit": 40.0,
        "epa_limit_str": "40 ppb",
        "ewg_limit": 0.7,
        "ewg_limit_str": "0.7 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the brain and nervous system; harm to the reproductive system",
    },
    "CARBON TETRACHLORIDE": {
        "epa_limit": 5.0,
        "epa_limit_str": "5 ppb",
        "ewg_limit": 0.1,
        "ewg_limit_str": "0.1 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the liver; harm to the central nervous system; decrease in fertility",
    },
    "CHLORATE": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 210.0,
        "ewg_limit_str": "210 ppb",
        "unit": "ppb",
        "source": "EPA Unregulated Contaminant Monitoring Rule benchmark",
        "health_effects": "Hormone disruption",
    },
    "CHLORDANE": {
        "epa_limit": 2.0,
        "epa_limit_str": "2 ppb",
        "ewg_limit": 0.03,
        "ewg_limit_str": "0.03 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; hormone disruption; harm to reproduction and child development",
    },
    "CHLORODIBROMOACETIC ACID": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.02,
        "ewg_limit_str": "0.02 ppb",
        "unit": "ppb",
        "source": "EWG-recommended health guideline",
        "health_effects": "Cancer; harm to fetal growth and development",
    },
    "CHLORITE": {
        "epa_limit": 1000.0,
        "epa_limit_str": "1 ppm",
        "ewg_limit": 50.0,
        "ewg_limit_str": "0.050 ppm",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Change to blood cells; change to the thyroid; hormone disruption",
    },
    "CHLOROFORM": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.4,
        "ewg_limit_str": "0.4 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to fetal growth and development",
    },
    "CHROMIUM (HEXAVALENT)": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.02,
        "ewg_limit_str": "0.02 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the liver; harm to the reproductive system",
    },
    "COBALT": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 70.0,
        "ewg_limit_str": "70 ppb",
        "unit": "ppb",
        "source": "EPA Unregulated Contaminant Monitoring Rule benchmark",
        "health_effects": "Harm to the heart; change in blood chemistry; harm to the stomach and intestines",
    },
    "COPPER": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 300.0,
        "ewg_limit_str": "300 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Diarrhea; weight loss; vomiting",
    },
    "CYANIDE": {
        "epa_limit": 200.0,
        "epa_limit_str": "200 ppb",
        "ewg_limit": 150.0,
        "ewg_limit_str": "150 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the brain and nervous system; harm to the thyroid",
    },
    "DI(2-ETHYLHEXYL) ADIPATE": {
        "epa_limit": 400.0,
        "epa_limit_str": "400 ppb",
        "ewg_limit": 200.0,
        "ewg_limit_str": "200 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Change to fetal growth and development; harm to the liver",
    },
    "DI(2-ETHYLHEXYL) PHTHALATE": {
        "epa_limit": 6.0,
        "epa_limit_str": "6 ppb",
        "ewg_limit": 3.0,
        "ewg_limit_str": "3 ppb",
        "unit": "ppb",
        "source": "One-in-a-million cancer risk standard",
        "health_effects": "Harm to the male reproductive system; harm to the immune system; hormone disruption",
    },
    "DIBROMOACETIC ACID": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.03,
        "ewg_limit_str": "0.03 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to fetal growth and development",
    },
    "DIBROMOCHLOROMETHANE": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.1,
        "ewg_limit_str": "0.1 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to fetal growth and development",
    },
    "DICHLOROACETIC ACID": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.2,
        "ewg_limit_str": "0.2 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to reproduction and child development",
    },
    "DICHLOROMETHANE": {
        "epa_limit": 5.0,
        "epa_limit_str": "5 ppb",
        "ewg_limit": 4.0,
        "ewg_limit_str": "4 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to reproduction and child development; harm to the liver",
    },
    "DIQUAT": {
        "epa_limit": 20.0,
        "epa_limit_str": "20 ppb",
        "ewg_limit": 6.0,
        "ewg_limit_str": "6 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Change to fetal growth and development; harm to the kidney; cataracts",
    },
    "ENDOTHALL": {
        "epa_limit": 100.0,
        "epa_limit_str": "100 ppb",
        "ewg_limit": 94.0,
        "ewg_limit_str": "94 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Change to the stomach and intestines; eye damage; skin irritation",
    },
    "ENDRIN": {
        "epa_limit": 2.0,
        "epa_limit_str": "2 ppb",
        "ewg_limit": 0.3,
        "ewg_limit_str": "0.3 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; change to the central nervous system; harm to the immune system",
    },
    "ETHYLBENZENE": {
        "epa_limit": 700.0,
        "epa_limit_str": "700 ppb",
        "ewg_limit": 300.0,
        "ewg_limit_str": "300 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the lungs; harm to the liver; harm to the kidney",
    },
    "ETHYLENE DIBROMIDE": {
        "epa_limit": 0.05,
        "epa_limit_str": "0.05 ppb",
        "ewg_limit": 0.01,
        "ewg_limit_str": "0.01 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the reproductive system; change to fetal growth and development",
    },
    "GLYPHOSATE": {
        "epa_limit": 700.0,
        "epa_limit_str": "700 ppb",
        "ewg_limit": 5.0,
        "ewg_limit_str": "5 ppb",
        "unit": "ppb",
        "source": "EWG-recommended health guideline",
        "health_effects": "Cancer; harm to fetal growth; harm to the kidney",
    },
    "HALOACETIC ACIDS (HAA5)": {
        "epa_limit": 60.0,
        "epa_limit_str": "60 ppb",
        "ewg_limit": 0.1,
        "ewg_limit_str": "0.1 ppb",
        "unit": "ppb",
        "source": "EWG-recommended health guideline",
        "health_effects": "Cancer; harm to fetal growth and development",
    },
    "HALOACETIC ACIDS (HAA9)": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.06,
        "ewg_limit_str": "0.06 ppb",
        "unit": "ppb",
        "source": "EWG-recommended health guideline",
        "health_effects": "Cancer; harm to fetal growth and development",
    },
    "HALOACETIC ACIDS (HAA6BR)": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.06,
        "ewg_limit_str": "0.06 ppb",
        "unit": "ppb",
        "source": "EWG-recommended health guideline",
        "health_effects": "Cancer; harm to fetal growth and development",
    },
    "HEPTACHLOR": {
        "epa_limit": 0.4,
        "epa_limit_str": "0.4 ppb",
        "ewg_limit": 0.008,
        "ewg_limit_str": "0.008 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; hormone disruption; harm to the brain and nervous system",
    },
    "HEPTACHLOR EPOXIDE": {
        "epa_limit": 0.2,
        "epa_limit_str": "0.2 ppb",
        "ewg_limit": 0.006,
        "ewg_limit_str": "0.006 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; hormone disruption; harm to the liver",
    },
    "HEXACHLOROBENZENE": {
        "epa_limit": 1.0,
        "epa_limit_str": "1 ppb",
        "ewg_limit": 0.03,
        "ewg_limit_str": "0.03 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the brain and nervous system; hormone disruption",
    },
    "HEXACHLOROCYCLOPENTADIENE": {
        "epa_limit": 50.0,
        "epa_limit_str": "50 ppb",
        "ewg_limit": 2.0,
        "ewg_limit_str": "2 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the stomach and intestines; change to the liver; irritation of the lungs",
    },
    "HFPO-DA": {
        "epa_limit": 10.0,
        "epa_limit_str": "10 ppt",
        "ewg_limit": 9.0,
        "ewg_limit_str": "9 ppt",
        "unit": "ppt",
        "source": "EPA Human Health toxicity value",
        "health_effects": "Harm to the liver",
    },
    "LEAD": {
        "epa_limit": 10.0,
        "epa_limit_str": "10 ppb (action level)",
        "ewg_limit": 0.2,
        "ewg_limit_str": "0.2 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the brain and nervous system",
    },
    "LINDANE": {
        "epa_limit": 0.2,
        "epa_limit_str": "0.2 ppb",
        "ewg_limit": 0.032,
        "ewg_limit_str": "0.032 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the brain and nervous system; harm to the immune system",
    },
    "MANGANESE": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 100.0,
        "ewg_limit_str": "100 ppb",
        "unit": "ppb",
        "source": "Minnesota Department of Health advisory level",
        "health_effects": "Harm to the brain and nervous system; change in behavior",
    },
    "MERCURY (INORGANIC)": {
        "epa_limit": 2.0,
        "epa_limit_str": "2 ppb",
        "ewg_limit": 1.2,
        "ewg_limit_str": "1.2 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the brain and nervous system; harm to fetal growth; harm to the kidney",
    },
    "METHOXYCHLOR": {
        "epa_limit": 40.0,
        "epa_limit_str": "40 ppb",
        "ewg_limit": 0.09,
        "ewg_limit_str": "0.09 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Hormone disruption; harm to the reproductive system; harm to the kidney; harm to the liver",
    },
    "MOLYBDENUM": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 40.0,
        "ewg_limit_str": "40 ppb",
        "unit": "ppb",
        "source": "EPA lifetime exposure health advisory",
        "health_effects": "Change in blood chemistry; gout",
    },
    "MONOBROMOACETIC ACID": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 25.0,
        "ewg_limit_str": "25 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Change to fetal growth and development",
    },
    "MONOCHLOROACETIC ACID": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 53.0,
        "ewg_limit_str": "53 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Change to fetal growth and development",
    },
    "MONOCHLOROBENZENE": {
        "epa_limit": 100.0,
        "epa_limit_str": "100 ppb",
        "ewg_limit": 70.0,
        "ewg_limit_str": "70 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the liver; harm to the kidney",
    },
    "MTBE": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 13.0,
        "ewg_limit_str": "13 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer",
    },
    "N-NITROSODIMETHYLAMINE (NDMA)": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.003,
        "ewg_limit_str": "0.003 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer",
    },
    "NITRATE": {
        "epa_limit": 10.0,
        "epa_limit_str": "10 ppm",
        "ewg_limit": 0.14,
        "ewg_limit_str": "0.14 ppm",
        "unit": "ppm",
        "source": "EWG-recommended health guideline",
        "health_effects": "Cancer; harm to fetal growth and child development",
    },
    "OXAMYL": {
        "epa_limit": 200.0,
        "epa_limit_str": "200 ppb",
        "ewg_limit": 26.0,
        "ewg_limit_str": "26 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the central nervous system; harm to child development",
    },
    "PENTACHLOROPHENOL": {
        "epa_limit": 1.0,
        "epa_limit_str": "1 ppb",
        "ewg_limit": 0.3,
        "ewg_limit_str": "0.3 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to child development; harm to the immune system; hormone disruption",
    },
    "PERCHLORATE": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 1.0,
        "ewg_limit_str": "1 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Hormone disruption; harm to fetal growth and child development",
    },
    "PFBS": {
        "epa_limit": None,
        "epa_limit_str": "Hazard Index only",
        "ewg_limit": 2000.0,
        "ewg_limit_str": "2 ppb",
        "unit": "ppt",
        "source": "EPA Human Health toxicity value",
        "health_effects": "Hormone disruption; harm to fetal growth and child development",
    },
    "PFBA": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 1000.0,
        "ewg_limit_str": "1 ppb",
        "unit": "ppt",
        "source": "EPA toxicity value",
        "health_effects": "Harm to fetal growth and child development",
    },
    "PFDA": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.006,
        "ewg_limit_str": "0.006 ppt",
        "unit": "ppt",
        "source": "EPA toxicity value",
        "health_effects": "Harm to the immune system; harm to fetal growth and child development",
    },
    "PFDS": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.001,
        "ewg_limit_str": "0.001 ppt",
        "unit": "ppt",
        "source": "EPA PFHxS toxicity value application",
        "health_effects": "Harm to the developing immune system",
    },
    "PFDOA": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.006,
        "ewg_limit_str": "0.006 ppt",
        "unit": "ppt",
        "source": "EPA PFDA toxicity value application",
        "health_effects": "Harm to the immune system; harm to fetal growth and child development",
    },
    "PFHPA": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 1000.0,
        "ewg_limit_str": "1 ppb",
        "unit": "ppt",
        "source": "EPA PFHxA toxicity value application",
        "health_effects": "Harm to fetal growth and child development",
    },
    "PFHPS": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.001,
        "ewg_limit_str": "0.001 ppt",
        "unit": "ppt",
        "source": "EPA PFHxS toxicity value application",
        "health_effects": "Harm to the developing immune system",
    },
    "PFHXS": {
        "epa_limit": 10.0,
        "epa_limit_str": "10 ppt (Hazard Index)",
        "ewg_limit": 0.001,
        "ewg_limit_str": "0.001 ppt",
        "unit": "ppt",
        "source": "EPA IRIS toxicity value",
        "health_effects": "Harm to the developing immune system",
    },
    "PFHXA": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 1000.0,
        "ewg_limit_str": "1 ppb",
        "unit": "ppt",
        "source": "EPA IRIS toxicity value",
        "health_effects": "Harm to fetal growth and child development",
    },
    "PFNA": {
        "epa_limit": 10.0,
        "epa_limit_str": "10 ppt (Hazard Index)",
        "ewg_limit": 0.006,
        "ewg_limit_str": "0.006 ppt",
        "unit": "ppt",
        "source": "EPA PFDA toxicity value application",
        "health_effects": "Harm to the immune system; harm to fetal growth and child development",
    },
    "PFOS": {
        "epa_limit": 4.0,
        "epa_limit_str": "4 ppt",
        "ewg_limit": 0.3,
        "ewg_limit_str": "0.3 ppt",
        "unit": "ppt",
        "source": "EPA final toxicity value",
        "health_effects": "Cardiovascular harm; harm to fetal growth",
    },
    "PFOSA": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.3,
        "ewg_limit_str": "0.3 ppt",
        "unit": "ppt",
        "source": "EPA final PFOS toxicity value",
        "health_effects": "Cardiovascular harm; harm to fetal growth",
    },
    "PFOA": {
        "epa_limit": 4.0,
        "epa_limit_str": "4 ppt",
        "ewg_limit": 0.09,
        "ewg_limit_str": "0.09 ppt",
        "unit": "ppt",
        "source": "EPA final toxicity value",
        "health_effects": "Harm to the immune system; harm to fetal growth and child development; increased cholesterol",
    },
    "PFPEA": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 1000.0,
        "ewg_limit_str": "1 ppb",
        "unit": "ppt",
        "source": "EPA PFHxA toxicity value application",
        "health_effects": "Harm to fetal growth and child development",
    },
    "PFTA": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.006,
        "ewg_limit_str": "0.006 ppt",
        "unit": "ppt",
        "source": "EPA PFDA toxicity value application",
        "health_effects": "Harm to the immune system; harm to fetal growth and child development",
    },
    "PFTRDA": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.006,
        "ewg_limit_str": "0.006 ppt",
        "unit": "ppt",
        "source": "EPA PFDA toxicity value application",
        "health_effects": "Harm to the immune system; harm to fetal growth and child development",
    },
    "PFUNA": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.006,
        "ewg_limit_str": "0.006 ppt",
        "unit": "ppt",
        "source": "EPA PFDA toxicity value application",
        "health_effects": "Harm to the immune system; harm to fetal growth and child development",
    },
    "PICLORAM": {
        "epa_limit": 500.0,
        "epa_limit_str": "500 ppb",
        "ewg_limit": 166.0,
        "ewg_limit_str": "166 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the liver; harm to the kidney; change to the reproductive system",
    },
    "POLYCHLORINATED BIPHENYLS (PCBS)": {
        "epa_limit": 0.5,
        "epa_limit_str": "0.5 ppb",
        "ewg_limit": 0.09,
        "ewg_limit_str": "0.09 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Breast cancer; prostate cancer; harm to the brain and nervous system; hormone disruption",
    },
    "RADIUM-226": {
        "epa_limit": 5.0,
        "epa_limit_str": "5 pCi/L (combined)",
        "ewg_limit": 0.05,
        "ewg_limit_str": "0.05 pCi/L",
        "unit": "pCi/L",
        "source": "California public health goal",
        "health_effects": "Cancer",
    },
    "RADIUM-228": {
        "epa_limit": 5.0,
        "epa_limit_str": "5 pCi/L (combined)",
        "ewg_limit": 0.019,
        "ewg_limit_str": "0.019 pCi/L",
        "unit": "pCi/L",
        "source": "California public health goal",
        "health_effects": "Cancer",
    },
    "SELENIUM": {
        "epa_limit": 50.0,
        "epa_limit_str": "50 ppb",
        "ewg_limit": 30.0,
        "ewg_limit_str": "30 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Hormone disruption; harm to child development; skin damage",
    },
    "SIMAZINE": {
        "epa_limit": 4.0,
        "epa_limit_str": "4 ppb",
        "ewg_limit": 0.1,
        "ewg_limit_str": "0.1 ppb",
        "unit": "ppb",
        "source": "EWG-recommended health guideline",
        "health_effects": "Harm to the developing fetus; hormone disruption; harm to the reproductive system; cancer",
    },
    "STRONTIUM": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 1500.0,
        "ewg_limit_str": "1.5 ppm",
        "unit": "ppb",
        "source": "EPA Unregulated Contaminant Monitoring Rule benchmark",
        "health_effects": "Harm to bones",
    },
    "STRONTIUM-90": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.35,
        "ewg_limit_str": "0.35 pCi/L",
        "unit": "pCi/L",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to bones",
    },
    "STYRENE": {
        "epa_limit": 100.0,
        "epa_limit_str": "100 ppb",
        "ewg_limit": 0.5,
        "ewg_limit_str": "0.5 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the liver; harm to the brain and nervous system",
    },
    "TETRACHLOROETHYLENE": {
        "epa_limit": 5.0,
        "epa_limit_str": "5 ppb",
        "ewg_limit": 0.06,
        "ewg_limit_str": "0.06 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Lung cancer; breast cancer; colon cancer; harm to the kidney; harm to the liver",
    },
    "THALLIUM": {
        "epa_limit": 2.0,
        "epa_limit_str": "2 ppb",
        "ewg_limit": 0.1,
        "ewg_limit_str": "0.1 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Hair loss; harm to the liver; harm to the central nervous system",
    },
    "TOLUENE": {
        "epa_limit": 1000.0,
        "epa_limit_str": "1 ppm",
        "ewg_limit": 150.0,
        "ewg_limit_str": "0.15 ppm",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the brain and nervous system; harm to the liver; harm to the reproductive system",
    },
    "TOTAL TRIHALOMETHANES (TTHMS)": {
        "epa_limit": 80.0,
        "epa_limit_str": "80 ppb",
        "ewg_limit": 0.15,
        "ewg_limit_str": "0.15 ppb",
        "unit": "ppb",
        "source": "EWG-recommended health guideline",
        "health_effects": "Bladder cancer; skin cancer; harm to fetal growth and development",
    },
    "TOXAPHENE": {
        "epa_limit": 3.0,
        "epa_limit_str": "3 ppb",
        "ewg_limit": 0.03,
        "ewg_limit_str": "0.03 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the brain and nervous system; hormone disruption",
    },
    "TRIBROMOACETIC ACID": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.04,
        "ewg_limit_str": "0.04 ppb",
        "unit": "ppb",
        "source": "EWG-recommended health guideline",
        "health_effects": "Change to fetal growth and development",
    },
    "TRICHLOROACETIC ACID": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 0.1,
        "ewg_limit_str": "0.1 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to reproduction and child development",
    },
    "TRICHLOROETHYLENE": {
        "epa_limit": 5.0,
        "epa_limit_str": "5 ppb",
        "ewg_limit": 0.4,
        "ewg_limit_str": "0.4 ppb",
        "unit": "ppb",
        "source": "Minnesota Department of Health advisory level",
        "health_effects": "Cancer; change to fetal growth and development; harm to the liver",
    },
    "TRITIUM": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 400.0,
        "ewg_limit_str": "400 pCi/L",
        "unit": "pCi/L",
        "source": "California public health goal",
        "health_effects": "Cancer",
    },
    "URANIUM": {
        "epa_limit": 30.0,
        "epa_limit_str": "30 ppb",
        "ewg_limit": 0.43,
        "ewg_limit_str": "0.43 pCi/L",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Cancer; harm to the kidney",
    },
    "VANADIUM": {
        "epa_limit": None,
        "epa_limit_str": "No legal limit",
        "ewg_limit": 21.0,
        "ewg_limit_str": "21 ppb",
        "unit": "ppb",
        "source": "EPA Unregulated Contaminant Monitoring Rule benchmark",
        "health_effects": "Change in blood chemistry; harm to reproduction and child development",
    },
    "VINYL CHLORIDE": {
        "epa_limit": 2.0,
        "epa_limit_str": "2 ppb",
        "ewg_limit": 0.05,
        "ewg_limit_str": "0.05 ppb",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Liver cancer; harm to the liver; change to the central nervous system",
    },
    "XYLENES (TOTAL)": {
        "epa_limit": 10000.0,
        "epa_limit_str": "10 ppm",
        "ewg_limit": 1800.0,
        "ewg_limit_str": "1.8 ppm",
        "unit": "ppb",
        "source": "California public health goal",
        "health_effects": "Harm to the brain and nervous system; change to fetal growth and development",
    },
}


def lookup(name: str) -> dict | None:
    """Case-insensitive lookup with partial match fallback."""
    key = name.upper().strip()
    if key in EWG_STANDARDS:
        return EWG_STANDARDS[key]
    # Partial match
    for k, v in EWG_STANDARDS.items():
        if key in k or k in key:
            return v
    return None
